### PR TITLE
Remove second button to corona-check website

### PR DESCRIPTION
**Pull request by maerki**

### CODE REVIEW

**Comment by joseph-elmallah** [comment]
This was added as part of a change request. Is it true we don’t want both anymore?

**Comment by maerki** [comment]
We don't want this button anymore, right @simonroesch ?

**Comment by simonroesch** [comment]
There was one link to the coronacheck previously, we added a second one this week, then we had two. We keep this new button, but remove the second old one that was previously there. So in the end the link should move from the additional info text up to the box.

**Comment by joseph-elmallah** [comment]
Ok 👌

**Pull request merged**
